#!/usr/bin/env bash
set -e -E -o pipefail

deviceCount=$(echo $( adb devices -l | grep "device " | wc -l ))
if [[ $deviceCount == 0 ]]; then
    echo "You must have a device connected";
    exit -1
fi

if [[ $deviceCount == 1 ]]; then
    deviceNum=1
else
    count=0
    adb devices -l | grep "device " | while read line ; do
        count=$((count+1))
        echo "($count) $line"g
    done
    echo -n "Device to connect to: "
    read deviceNum
fi

device=$(adb devices -l | grep "device " | head "-$deviceNum" | tail -1 | cut -d' ' -f1)

IP=$(adb -s $device shell ip route | awk '{print $9}' | tail -1)
adb -s $device tcpip 5555

echo "Unplug USB now 3"
sleep 1s
echo "Unplug USB now 2"
sleep 1s
echo "Unplug USB now 1"

adb -s $device connect $(echo "$IP:5555")
